services:
  node:
    build:
      context: ./node
    container_name: game-list-node
    ports:
      - "5173:5173"
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    volumes:
      - ./app:/app
